#!/bin/zsh
#
# Use keychain to start and manage ssh-agent
#

sj_setup_ssh_agent() {
  local kcfiles keyhost
  keyhost=sudish        # use a fixed hostname, no nfs here
 
  if [[ `whoami` == 'sj' || `whoami` == 'sudish' ]]; then
    kcfiles=()
    for keyfile in `cat ~/.ssh/agent-keyfiles 2>/dev/null`; do
      [[ -r ~/.ssh/$keyfile ]] && kcfiles+="$keyfile"
    done
    if [[ -n $kcfiles ]] ; then
      # For running at shell startup use this variant
      #eval $(keychain add --eval --host "$keyhost" -q --immediate --quick "$kcfiles[@]")
      # This is more suited to running interactively, on-demand
      eval $(keychain add --eval --host "$keyhost" "$kcfiles[@]")
    fi
  fi
}

# Don't autostart ssh-agent anymore, rather do it manually only when needed
#sj_setup_ssh_agent
alias kc=sj_setup_ssh_agent
