# Device: Flydigi Vader 5 Pro
name = "Crimson Desert:Vader 5 Pro"
trigger_threshold = 100

[remap]
# M1 = layer, mainly RB+button combos       # right front paddle
# M2 = layer, mainly LB+button combos       # left front paddle
M3 = "RS"                                   # right back paddle
M4 = "LS"                                   # left back paddle
RM = "RB"                                   # right extra bumper
LM = "LB"                                   # left extra bumper
# RB = left as is
# LB = left as is

# I click LS/RS inadvertently, unmap
LS = "disabled"
RS = "disabled"

# Menu screens
C = "KEY_M"                                 # Map
Z = "KEY_I"                                 # Inventory

[gyro]
mode        = "joystick"  # "joystick", "mouse" or "off"
blend_stick = true
target      = "right_stick"
activate    = "LT"
sensitivity = 50.0
deadzone    = 10
smoothing   = 0.1
invert_y    = true

# CD's window for button chords is too tight plus RB is an action in
# addition to effectively being a chording key. This makes RB+button
# combos tough to pull off consistently, sometimes whiffing into light
# attacks instead.
#
# This layer makes RB+button chords feel more consistent by removing
# the overload of RB as both an attack button and a chording button.
# The layer handles chords letting RB be just an attack button.
[[layer]]
name = "skills 1"
trigger = "M1"                              # right front paddle
activation = "hold"
hold_timeout = 1

[layer.remap]
# These mimic default RB+button bindings
RT = "macro:turning_slash"
X  = "macro:unarmed"
Y  = "macro:stab"
A  = "macro:spinning_slash"
B  = "macro:evasive_slash"
# New bindings for convenience
M2 = "RB"                                   # light attack, for combos
LB = "macro:focus_mode"

# Do the same things for LB+button chords.
[[layer]]
name = "skills 2"
trigger = "M2"                              # left front paddle
activation = "hold"
hold_timeout = 1

[layer.remap]
# These mimic default LB+button bindings
RT = "macro:shield_bash"
LT = "macro:switch_weapon"
# New bindings for convenience
M1 = "RB"                                   # light attack, for combos
X  = "macro:unarmed"
RB = "macro:blinding_flash"

# Menu screens
C = "KEY_K"                                 # Skills
Z = "KEY_J"                                 # Journal
Start = "KEY_P"                             # Photo mode

[[macro]]
name = "blinding_flash"
steps = [ { press = "RB" }, { press = "LB" }, "pause_for_release" ]

[[macro]]
name = "unarmed"
steps = [ { press = "RB" }, { press = "X" }, "pause_for_release" ]

[[macro]]
name = "stab"
steps = [ { press = "RB" }, { press = "Y" }, "pause_for_release" ]

[[macro]]
name = "spinning_slash"
steps = [ { press = "RB" }, { press = "A" }, "pause_for_release" ]

[[macro]]
name = "evasive_slash"
steps = [ { press = "RB" }, { press = "B" }, "pause_for_release" ]

[[macro]]
name = "turning_slash"
steps = [ { press = "RB" }, { press = "RT" }, "pause_for_release" ]

[[macro]]
name = "shield_bash"
steps = [ { press = "LB" }, { press = "RT" }, "pause_for_release" ]

[[macro]]
name = "switch_weapon"
steps = [ { press = "LB" }, { press = "LT" }, "pause_for_release" ]

[[macro]]
name = "focus_mode"
steps = [ { press = "LS" }, { press = "RS" }, "pause_for_release" ]
