name = "Nioh"
trigger_threshold = 100

[remap]
# I tend to click LS/RS inadvertently, unmap
LS = "disabled"
RS = "disabled"

M1 = "RB"                                   # right front paddle
M2 = "LB"                                   # Left front paddle
M3 = "RS"                                   # right back paddle
M4 = "LS"                                   # left back paddle
RM = "RB"                                   # right extra bumper
LM = "LB"                                   # left extra bumper
# RB = left as is
# LB = left as is

C = "disabled"
Z = "disabled"

[gyro]
mode        = "joystick"  # "joystick", "mouse" or "off"
blend_stick = true
target      = "right_stick"
activate    = "LT"
sensitivity = 200.0
deadzone    = 10
smoothing   = 0.1
invert_y    = true

# RB is Ki Pulse + stance chord so set up a layer for just stances
[[layer]]
name = "stances+"
trigger = "M4"                              # left back paddle
activation = "hold"
hold_timeout = 1

[layer.remap]
# Stances
Y  = "macro:high_stance"
X  = "macro:medium_stance"
A  = "macro:low_stance"
B  = "macro:sheathe"

# Add direct buttons for the stances, makes it much simpler
[[macro]]
name = "high_stance"
steps = [ { press = "RB" }, { press = "Y" }, "pause_for_release" ]

[[macro]]
name = "medium_stance"
steps = [ { press = "RB" }, { press = "X" }, "pause_for_release" ]

[[macro]]
name = "low_stance"
steps = [ { press = "RB" }, { press = "A" }, "pause_for_release" ]

[[macro]]
name = "sheathe"
steps = [ { press = "RB" }, { press = "B" }, "pause_for_release" ]
